layouter/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from layouter.views import ToggleGridView
from django.urls import path

urlpatterns = [
    path('toggle-grid/', ToggleGridView.as_view(), name='toggle-grid')
]

layouter/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.safestring import mark_safe
from cms.models.pluginmodel import CMSPlugin
from easy_thumbnails.files import get_thumbnailer
from filer.fields.image import FilerImageField
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import force_str
from six import python_2_unicode_compatible


@python_2_unicode_compatible
class ContainerPlugin(CMSPlugin):

    FULL_WIDTH = 100
    THREE_QUARTER_WIDTH = 75
    TWO_THIRD_WIDTH = 66
    HALF_WIDTH = 50
    THIRD_WIDTH = 33
    QUARTER_WIDTH = 25

    NO_MARGIN = _('No margin')
    ONE_COL_MARGIN = '8.33%'
    TWO_COL_MARGIN = '16.66%'
    THREE_COL_MARGIN = '25%'
    FOUR_COL_MARGIN = '33.33%'

    CONTAINER_TYPES = [
        (0, _('One tile - full width')),
        (1, _('Two tiles - 50 | 50')),
        (2, _('Two tiles - 25 | 75')),
        (3, _('Two tiles - 75 | 25')),
        (4, _('Two tiles - 33 | 66')),
        (5, _('Two tiles - 66 | 33')),
        (6, _('Three tiles - 33 | 33 | 33')),
        (7, _('Three tiles - 25 | 25 | 50')),
        (8, _('Three tiles - 25 | 50 | 25')),
        (9, _('Three tiles - 50 | 25 | 25')),
        (10, _('Four tiles - 25 | 25 | 25 | 25')),
    ]

    TYPE_COLUMNS = {
        0: [FULL_WIDTH],
        1: [HALF_WIDTH, HALF_WIDTH],
        2: [QUARTER_WIDTH, THREE_QUARTER_WIDTH],
        3: [THREE_QUARTER_WIDTH, QUARTER_WIDTH],
        4: [THIRD_WIDTH, TWO_THIRD_WIDTH],
        5: [TWO_THIRD_WIDTH, THIRD_WIDTH],
        6: [THIRD_WIDTH, THIRD_WIDTH, THIRD_WIDTH],
        7: [QUARTER_WIDTH, QUARTER_WIDTH, HALF_WIDTH],
        8: [QUARTER_WIDTH, HALF_WIDTH, QUARTER_WIDTH],
        9: [HALF_WIDTH, QUARTER_WIDTH, QUARTER_WIDTH],
        10: [QUARTER_WIDTH, QUARTER_WIDTH, QUARTER_WIDTH, QUARTER_WIDTH]
    }

    MARGIN_TYPES = (
        (0, NO_MARGIN),
        (1, ONE_COL_MARGIN),
        (2, TWO_COL_MARGIN),
        (3, THREE_COL_MARGIN),
        (4, FOUR_COL_MARGIN)
    )

    NO_PARALLAX = 0
    CSS_PARALLAX = 1
    TRUE_PARALLAX = 2
    BACKGROUND_IMAGE_PARALLAX_CHOICES = (
        (NO_PARALLAX, _('No effect')),
        (CSS_PARALLAX, _('Static background image')),
        (TRUE_PARALLAX, _('Parallax background image')),
    )

    container_type = models.IntegerField(choices=CONTAINER_TYPES, null=False, blank=False, default=TYPE_COLUMNS[0])

    margin = models.IntegerField(choices=MARGIN_TYPES, null=False, blank=False, default=MARGIN_TYPES[0][0],
                                 help_text=_('How much margin is needed on the left and right side?'))

    background_image = FilerImageField(
        verbose_name=_('Background image'),
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )

    background_image_parallax = models.IntegerField(_('Parallax Effect'), null=False, blank=False,
                                                    choices=BACKGROUND_IMAGE_PARALLAX_CHOICES, default=NO_PARALLAX)

    background_image_width = models.IntegerField(_('Background image width'), null=True, blank=True, default=1920)
    background_image_height = models.IntegerField(_('Background image width'), null=True, blank=True, default=1080,
                                                  help_text=_('It is recommended to limit the size of the background '
                                                              'image to a reasonable number in order to reduce page '
                                                              'loading times.'))

    # To achieve same height columns we use the CSS3 flex box grid. For more information about it have a look at
    # http://caniuse.com/flexbox
    equal_height = models.BooleanField(verbose_name=_('Align Content Height'),
                                       help_text=_('Align height of all columns in this row. Please note: '
                                                   'This setting is not  supported by Internet Explorer 9 and below.'),
                                       null=False, blank=False, default=False)

    css_classes = models.CharField(max_length=512, blank=True, null=True)

    @property
    def max_children(self):
        return len(self.TYPE_COLUMNS[self.container_type])

    def get_resized_background_image(self):
        """
        :return: The image which is thumbnailed to the specified size via easy-thumbnails
        """
        if self.background_image is None:
            return None

        thumbnail_options = {
            'crop': False,
            'size': (self.background_image_width, self.background_image_height)
        }
        try:
            thumbnailer = get_thumbnailer(self.background_image)
            image = thumbnailer.get_thumbnail(thumbnail_options)
        except:
            return None
        else:
            return image

    def clean(self):
        super(ContainerPlugin, self).clean()
        if self.background_image_parallax is not self.NO_PARALLAX and not self.background_image:
            raise ValidationError(
                _('You need to specify a background image in order to use a parallax effect.')
            )

    def __str__(self):
        name = self.CONTAINER_TYPES[self.container_type][1]
        if self.num_children() > self.max_children:
            name = '<span style="color:red">Warning, too many tiles!</span> {}'.format(name)

        return mark_safe(force_str(name))

layouter/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.widgets import RadioSelect, CheckboxInput
from layouter.models import ContainerPlugin
from django.utils.safestring import mark_safe


class ButtonSelectWidget(RadioSelect):
    FONT_MAPPER = {
        ContainerPlugin.FULL_WIDTH: u'full-width',
        ContainerPlugin.THREE_QUARTER_WIDTH: u'three-quarter',
        ContainerPlugin.TWO_THIRD_WIDTH: u'two-third',
        ContainerPlugin.HALF_WIDTH: u'half',
        ContainerPlugin.THIRD_WIDTH: u'third',
        ContainerPlugin.QUARTER_WIDTH: u'quarter',
    }
    option_template_name = 'layouter/radio_option.html'

    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        o = super(ButtonSelectWidget, self).create_option(name, value, label, selected, index, subindex, attrs)
        o['columns'] = [self.FONT_MAPPER[f] for f in ContainerPlugin.TYPE_COLUMNS[int(value)]]
        return o


class DeviceIconCheckBoxWidget(CheckboxInput):
    ICON_MAPPING = {
        'disable_on_mobile': '<i class="fa layouter-deviceIcon fa-mobile" aria-hidden="true"></i>',
        'disable_on_tablet': '<i class="fa layouter-deviceIcon fa-tablet" aria-hidden="true"></i>',
        'disable_on_desktop': '<i class="fa layouter-deviceIcon fa-desktop" aria-hidden="true"></i>',
    }

    def render(self, name, value, attrs=None):
        rendered_input = super(DeviceIconCheckBoxWidget, self).render(name, value, attrs)
        rendered_icon = mark_safe(self.ICON_MAPPING.get(name))
        return '{}{} '.format(rendered_input, rendered_icon)


class ContainerPluginForm(forms.ModelForm):
    class Meta:
        model = ContainerPlugin
        fields = ['container_type']
        widgets = {
            'container_type': ButtonSelectWidget,
            'disable_on_mobile': DeviceIconCheckBoxWidget,
            'disable_on_tablet': DeviceIconCheckBoxWidget,
            'disable_on_desktop': DeviceIconCheckBoxWidget,
        }

    def clean(self):
        cleaned_data = super(ContainerPluginForm, self).clean()
        if cleaned_data['css_classes']:
            cleaned_data['css_classes'] = cleaned_data['css_classes'].strip()
        return cleaned_data

layouter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http.response import JsonResponse
from django.views.generic.base import View


class ToggleGridView(View):

    def post(self, request, *args, **kwargs):
        # If a post is placed here, toggle the layouter_grid in the session.
        # This causes the button in the toolbar to be active or inactive and the grid to be shown or hidden.
        request.session['layouter_grid'] = not bool(request.session.get('layouter_grid'))
        # Return the result as JSON.
        res = {'show_grid': request.session['layouter_grid']}
        return JsonResponse(res, status=200)

layouter/templates/layouter/bootstrap3/container.html
<div class="row layouterRow--outer">
    <div class="col-md-offset-{{ instance.margin }} col-md-{{ width }}">
        <div class="row layouterRow--inner
        {% if request.session.layouter_grid %}show-grid{% endif %}
        {% if instance.equal_height %}layouterRow--equalHeight{% endif %}

        {% if instance.background_image_parallax == instance.CSS_PARALLAX %}layouterRow--parallax{% endif %}
        {% if instance.background_image_parallax == instance.TRUE_PARALLAX %}js-layouterRow--parallax{% endif %}

        {{ instance.css_classes }}"

        {% if instance.background_image %}
            {% if instance.background_image_parallax == instance.TRUE_PARALLAX %}
                {# Setup True / JS Parallax via parallax.js #}
                 data-parallax="scroll" data-image-src="{{ instance.get_resized_background_image.url }}"
                 data-naturalWidth="{{ instance.get_resized_background_image.width }}"
                 data-naturalHeigth="{{ instance.get_resized_background_image.height }}"
            {% else %}
                {# CSS_PARALLAX also uses the background image #}
                style="background-image: url('{{ instance.get_resized_background_image.url }}')"
            {% endif %}
        {% endif %}">
            {% include 'layouter/bootstrap3/partials/one_col.html' %}
            {% include 'layouter/bootstrap3/partials/two_cols.html' %}
            {% include 'layouter/bootstrap3/partials/three_cols.html' %}
            {% include 'layouter/bootstrap3/partials/four_cols.html' %}
        </div>
    </div>
</div>
{% include "layouter/partials/layouter_javascript.html" %}

layouter/templates/layouter/bootstrap3/partials/four_cols.html
{% load cms_tags %}

{% if instance.container_type == 10 %}
    {% for plugin in instance.child_plugin_instances %}
        <div class="col-md-3 col-sm-6">
            {% render_plugin plugin %}
        </div>
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap3/partials/one_col.html
{% load cms_tags %}
{% if instance.container_type == 0 %}
    {% for plugin in instance.child_plugin_instances %}
        <div class="col-md-12">
            {% render_plugin plugin %}
        </div>
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap3/partials/three_cols.html
{% load cms_tags %}

{% if instance.container_type == 6 %}
    {% for plugin in instance.child_plugin_instances %}
        <div class="col-md-4">
            {% render_plugin plugin %}
        </div>
    {% endfor %}
{% elif instance.container_type == 7 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-3 col-sm-6">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-3 col-sm-6">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 3 %}
            <div class="col-md-6 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 8 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-3 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-6 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 3 %}
            <div class="col-md-3 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 9 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-6 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-3 col-sm-6">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 3 %}
            <div class="col-md-3 col-sm-6">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap3/partials/two_cols.html
{% load cms_tags %}

{% if instance.container_type == 1 %}
    {% for plugin in instance.child_plugin_instances %}
            <div class="col-md-6 col-sm-12">
                {% render_plugin plugin %}
            </div>
    {% endfor %}
{% elif instance.container_type == 2 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-3 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-9 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 3 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-9 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-3 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 4 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-4 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-8 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 5 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-md-8 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-4 col-sm-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-md-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap4/container.html
<div class="row layouterRow--outer">
    <div class="offset-lg-{{ instance.margin }} col-lg-{{ width }}">
        <div class="row layouterRow--inner
        {% if request.session.layouter_grid %}show-grid{% endif %}
        {% if not instance.equal_height %}align-items-start{% endif %}

        {% if instance.background_image_parallax == instance.CSS_PARALLAX %}layouterRow--parallax{% endif %}
        {% if instance.background_image_parallax == instance.TRUE_PARALLAX %}js-layouterRow--parallax{% endif %}

        {{ instance.css_classes }}"

        {% if instance.background_image %}
            {% if instance.background_image_parallax == instance.TRUE_PARALLAX %}
                {# Setup True / JS Parallax via parallax.js #}
                 data-parallax="scroll" data-image-src="{{ instance.get_resized_background_image.url }}"
                 data-naturalWidth="{{ instance.get_resized_background_image.width }}"
                 data-naturalHeigth="{{ instance.get_resized_background_image.height }}"
            {% else %}
                {# CSS_PARALLAX also uses the background image #}
                style="background-image: url('{{ instance.get_resized_background_image.url }}')"
            {% endif %}
        {% endif %}
        >
            {% include 'layouter/bootstrap4/partials/one_col.html' %}
            {% include 'layouter/bootstrap4/partials/two_cols.html' %}
            {% include 'layouter/bootstrap4/partials/three_cols.html' %}
            {% include 'layouter/bootstrap4/partials/four_cols.html' %}
        </div>
    </div>
</div>
{% include "layouter/partials/layouter_javascript.html" with instance=instance %}

layouter/templates/layouter/bootstrap4/partials/four_cols.html
{% load cms_tags %}

{% if instance.container_type == 10 %}
    {% for plugin in instance.child_plugin_instances %}
        <div class="col-xl-3 col-md-6 col-12">
            {% render_plugin plugin %}
        </div>
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap4/partials/one_col.html
{% load cms_tags %}
{% if instance.container_type == 0 %}
    {% for plugin in instance.child_plugin_instances %}
        <div class="col-12">
            {% render_plugin plugin %}
        </div>
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap4/partials/three_cols.html
{% load cms_tags %}

{% if instance.container_type == 6 %}
    {% for plugin in instance.child_plugin_instances %}
        <div class="col-12 col-md-4">
            {% render_plugin plugin %}
        </div>
    {% endfor %}
{% elif instance.container_type == 7 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-12 col-md-6 col-lg-3">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-12 col-md-6 col-lg-3">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 3 %}
            <div class="col-12 col-lg-6">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 8 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-lg-3 col-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-lg-6 col-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 3 %}
            <div class="col-lg-3 col-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 9 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-12 col-lg-6">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-12 col-md-6 col-lg-3">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 3 %}
            <div class="col-12 col-md-6 col-lg-3">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

layouter/templates/layouter/bootstrap4/partials/two_cols.html
{% load cms_tags %}

{% if instance.container_type == 1 %}
    {% for plugin in instance.child_plugin_instances %}
            <div class="col-lg-6 col-12">
                {% render_plugin plugin %}
            </div>
    {% endfor %}
{% elif instance.container_type == 2 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-lg-3 col-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-lg-9 col-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 3 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-lg-9 col-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-lg-3 col-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 4 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-lg-4 col-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-lg-8 col-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% elif instance.container_type == 5 %}
    {% for plugin in instance.child_plugin_instances %}
        {% if forloop.first %}
            <div class="col-lg-8 col-12">
                {% render_plugin plugin %}
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-lg-4 col-12">
                {% render_plugin plugin %}
            </div>
        {% else %}
            <div class="col-12">
                {% render_plugin plugin %}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

layouter/templates/layouter/change_form.html
{% extends 'admin/cms/extensions/change_form.html' %}
{% load static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'layouter/css/layouter.css' %}">
{% endblock %}
{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script>
    var $ = django.jQuery;
    var container =$('#id_container_type');
    var $radios = container.find('input:radio');
    // Check currently selected value
    var $checkedRadio = container.find('input:checked');
    $($checkedRadio).parents('li').addClass('checked');

    // Listen on radio changes
    $radios.change(function () {
        $radios.parents('li').removeClass('checked');
        $(this).parents('li').addClass('checked');
    });
    </script>
{% endblock %}

layouter/templates/layouter/partials/layouter_css_and_javascript.html
{% load sekizai_tags staticfiles %}

{% addtoblock 'css' %}
    <link rel="stylesheet" href="{% static 'layouter/css/layouter.css' %}">

    {% if instance.bootstrap_version == 3 %}
        <link rel="stylesheet" href="{% static 'layouter/css/layouter-bootstrap3-specific.css' %}">
    {% elif instance.bootstrap_version == 4 %}
        <link rel="stylesheet" href="{% static 'layouter/css/layouter-bootstrap4-specific.css' %}">
    {% endif %}
{% endaddtoblock %}

{# The following JavaScript and CSS is only needed in editing mode #}
{% if request.toolbar.edit_mode %}
    {% csrf_token %}
    {% addtoblock 'css' %}
        <link rel="stylesheet" href="{% static 'layouter/css/layouter-editor.css' %}">
    {% endaddtoblock %}
    {% addtoblock 'js' %}
        <script>
            var toggleGridURL = '{% url 'layouter:toggle-grid' %}';
        </script>
        <script src="{% static 'layouter/js/layouter.js' %}" defer></script>
    {% endaddtoblock %}
{% endif %}

layouter/templates/layouter/partials/layouter_javascript.html
{% load sekizai_tags static %}

{# The following JavaScript and Styles are only needed in editing mode. #}
{% if request.toolbar.edit_mode %}
    {% csrf_token %}
    {% addtoblock 'css' %}
        <link rel="stylesheet" href="{% static 'layouter/css/layouter.css' %}">
    {% endaddtoblock %}
    {% addtoblock 'js' %}
        <script>
            var toggleGridURL = '{% url 'layouter:toggle-grid' %}';
        </script>
        <script src="{% static 'layouter/js/layouter.js' %}" defer></script>
    {% endaddtoblock %}
{% endif %}

{% if instance.background_image_parallax == instance.TRUE_PARALLAX %}
    {% addtoblock 'js' %}
        {# https://pixelcog.github.io/parallax.js/ #}
        <script src="{% static 'layouter/js/parallax.min.js' %}"></script>
        <script>
            $('.js-layouterRow--parallax').parallax();
        </script>
    {% endaddtoblock %}
{% endif %}

layouter/templates/layouter/radio_option.html
<label{% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}>
{% for column in widget.columns %}
<span class="icon-admin {{ column }}"></span>
{% endfor %}
<br/>
{% include "django/forms/widgets/input.html" %} {{ widget.label }}</label>